# Generated by Django 4.2.4 on 2023-08-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('limit', models.IntegerField()),
                ('allow_wired', models.BooleanField()),
                ('allow_mobile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time_span', models.DateField(auto_now_add=True)),
                ('api_usage_patreon_quota', models.IntegerField(default=0)),
                ('api_usage_patreon_cached', models.IntegerField(default=0)),
                ('api_usage_patreon_exceeded', models.IntegerField(default=0)),
                ('api_usage_patreon_not_allowed', models.IntegerField(default=0)),
                ('patreon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount')),
            ],
        ),
    ]
