# Generated by Django 4.2.4 on 2023-08-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='api_usage_patreon_not_allowed',
            new_name='api_usage_patreon_not_allowed_mobile',
        ),
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_not_allowed_wired',
            field=models.IntegerField(default=0),
        ),
    ]
