# Generated by Django 4.2.4 on 2023-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_api_usage_patreon_not_allowed_quota_api_usage_patreon_not_allowed_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='api_usage_patreon_exceeded',
            new_name='api_usage_patreon_exceeded_cached',
        ),
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_exceeded_notfound',
            field=models.IntegerField(default=0),
        ),
    ]
