# Generated by Django 4.2.4 on 2023-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_api_usage_patreon_exceeded_cached_quota_api_usage_patreon_exceeded_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_bdc_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_ipapi_failed',
            field=models.IntegerField(default=0),
        ),
    ]
