# Generated by Django 4.2.4 on 2023-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quota_api_usage_patreon_bdc_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='plan_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
