# Generated by Django 4.2.4 on 2023-09-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tier_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tier',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
    ]
