# Generated by Django 4.2.4 on 2023-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tier_limit_alter_tier_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_not_requested_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quota',
            name='api_usage_patreon_not_requested_wired',
            field=models.IntegerField(default=0),
        ),
    ]
