version: "3.8"

services:
  stats-monitor:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "47977:8000"
    env_file:
      - prod.env
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    volumes:
      - ./certs:/root/certs
