version: "3.3"

services:
  backend:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "443:8000"
    env_file:
      - .env
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
    entrypoint: "/bin/sh /root/prod.sh"
    volumes:
      - ./backend:/root
      - ./certs:/root/certs
